export const REGISTER_STORE = "REGISTER_STORE";

export const SET_STORE_ERROR = "SET_STORE_ERROR";

export const SET_SLOTS = "SET_SLOTS";

export const SET_STORE = "SET_STORE";

export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const SET_CATEGORIES = "SET_CATEGORIES";

export const SET_INACTIVE_SLOTS = "SET_INACTIVE_SLOTS";
