export const REGISTER_STORE = "REGISTER_STORE";

export const SET_STORE_ERROR = "SET_STORE_ERROR";

export const SET_SLOTS = "SET_SLOTS";

export const ADD_STORE_OWNER = "ADD_STORE_OWNER";

export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";

export const AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE";

export const SET_STORE = "SET_STORE";

export const FETCH_CATEGORIES = "FETCH_CATEGORIES";

export const SET_CATEGORIES = "SET_CATEGORIES";
